[package]
name = "gravity"
version = "0.1.0"
authors = ["Bruflot <idar@bruflot.io>"]
description = "Rust bindings for the Gravity API"
repository = "https://github.com/Bruflot/gravity-rs.git"
license = "MIT"
build = "build.rs"
